### ISSUE TITLE
Players without permissions can lock chests

### ISSUE THREAD

**Issue by L4BORG** [connection-lost/LockettePro#46] opened 2017-06-15 21:47 UTC
When creating new Lockette sign you put extra white spaces after "[private]" and it allows you to create private signs even if you don't have permissions for it. You also have to type your username in second line in order this to work.

**Comment by connection-lost** [comment] 2017-06-16 14:40
Does the plugin alerts the player that "You cannot lock this block"?

**Comment by connection-lost** [comment] 2017-06-16 14:43
Should fixed in https://github.com/connection-lost/LockettePro/commit/75e154aa3143754b889cfe782d965f7270423e35

**Closed** 2017-06-16 14:42 UTC

**Comment by L4BORG** [comment] 2017-06-16 15:34
The issue is still there.

**Comment by L4BORG** [comment] 2017-06-16 15:36
If username is tester for example, the player would have to do the following to replicate the issue:

https://i.imgur.com/0oXcfi3.png

**Comment by L4BORG** [comment] 2017-06-16 15:37
The can't create "normal signs" tho... and once those signs are created they can't remove them.

**Comment by connection-lost** [comment] 2017-06-17 12:11
nonono, that fixed version is not released yet

**Comment by L4BORG** [comment] 2017-06-17 12:21
Oh, well I compiled this version (from source from github) and I was still able to create sign without permissions.

**Comment by connection-lost** [comment] 2017-06-17 12:24
:(

**Comment by connection-lost** [comment] 2017-06-17 12:30
Tested but not a problem on my side though.
![img](http://i.imgur.com/KYJkmrl.png)

**Comment by connection-lost** [comment] 2017-06-17 12:31
Sorry for something I did very wrong

**Comment by connection-lost** [comment] 2017-06-17 12:35
Sorry for misunderstood your question. I just tried with Minecraft 1.12 with LockettePro 2.8.1 but your steps cannot reproduce the issue. 
Can you try the following...
1. Can you tell me your Minecraft version?
2. After create the "[private](space)" sign, can you spot the white space after the sign? You should look into it very carefully... If there is a white space, the "[private]" world will be shifted to the left a little bit.

**Comment by L4BORG** [comment] 2017-06-17 13:02
[private]+a lot of spaces... like this: https://imgur.com/0oXcfi3

we're using latest taco/paperspigot 1.8.8

**Comment by connection-lost** [comment] 2017-06-17 13:03
Will those space go away after you click done? I assume yes.

**Comment by L4BORG** [comment] 2017-06-17 13:04
Yes

**Comment by connection-lost** [comment] 2017-06-17 13:14
That was... very bad. It is not an intentional behavior...

**Comment by connection-lost** [comment] 2017-06-17 13:29
I was thinking about this for 10 minutes straight but I cannot find a good solution for this. The root cause of this issue is that the server should not trim the white space. But here is a band-aid patch for now, it should not break anything else. https://github.com/connection-lost/LockettePro/commit/6bf52b2da1d88916afba1a16ad04b3b35b83bb7e

**Comment by L4BORG** [comment] 2017-09-15 11:15
Was this pushed onto spigotmc? Because it seems like it's still bugged on latest LockettePro
